INSERT INTO party (NAME, IMAGE, TOTAL, CREATED_DATE) VALUES ('ยังไม่ได้นอนเลยยยยย', null, 1, CURRENT_TIMESTAMP);
INSERT INTO party (NAME, IMAGE, TOTAL, CREATED_DATE) VALUES ('วันหยุดไปไหนดี', null, 2, CURRENT_TIMESTAMP);
INSERT INTO party (NAME, IMAGE, TOTAL, CREATED_DATE) VALUES ('ง่วงมากมายยยยยย', null, 5,  CURRENT_TIMESTAMP);
INSERT INTO party (NAME, IMAGE, TOTAL, CREATED_DATE) VALUES ('หน้ากากอนามัย 30 ห่อ', null, 6, CURRENT_TIMESTAMP);
